/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "secondary-container": "#fd9a73",
        "surface-variant": "#e5e2e1",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed": "#ffdbce",
        "on-surface": "#1c1b1b",
        "primary-container": "#cc4900",
        "outline": "#8e7166",
        "surface-container": "#f0edec",
        "primary-fixed-dim": "#ffb599",
        "on-primary-fixed": "#370e00",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#313030",
        "outline-variant": "#e2bfb3",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#783112",
        "inverse-primary": "#ffb599",
        "secondary-fixed-dim": "#ffb599",
        "surface-tint": "#a73a00",
        "on-surface-variant": "#5a4138",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#763011",
        "error": "#ba1a1a",
        "surface-container-high": "#ebe7e7",
        "on-tertiary-container": "#fdfcff",
        "tertiary-container": "#0078c8",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#9ecaff",
        "surface-container-low": "#f6f3f2",
        "tertiary": "#005fa0",
        "on-secondary-fixed": "#370e00",
        "inverse-on-surface": "#f3f0ef",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d1e4ff",
        "on-primary-fixed-variant": "#802a00",
        "on-background": "#1c1b1b",
        "surface-dim": "#dcd9d9",
        "on-tertiary-fixed": "#001d36",
        "on-secondary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-tertiary-fixed-variant": "#00497d",
        "secondary-fixed": "#ffdbce"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        pulse: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.5 },
        },
        blink: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        blink: "blink 1s step-end infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
