// Compatibility facade. New code should import from @ocean/contracts.
export type {
  ToolResult,
  UIApprovalCard,
  UIApprovalCardProps,
  UIAttachment,
  UIBase,
  UIBugCard,
  UIBugCardProps,
  UIBugList,
  UIBugListProps,
  UICodeBlock,
  UICodeBlockProps,
  UIComponentType,
  UIPipelineCard,
  UIPipelineCardProps,
  UIStatsCard,
  UIStatsCardProps,
  UIStatsMetric,
  UIStep,
  UITaskPlan,
  UITaskPlanProps,
  UITaskStep,
  UIText,
  UITextProps,
  UIKit,
} from '@ocean/contracts';
